import { CompanyContext } from './types'

export const electronicsImportPressure: CompanyContext = {
  companyName: 'Harbour & Finch Trading Ltd.',
  sector: 'Electronics Import / Trading & Distribution',
  geography: 'HK / GBA',
  dataMode: 'connected_workspace',
  revenueTtmHkd: 42800000,
  cashBalanceHkd: 3200000,
  receivablesHkd: 8900000,
  payablesHkd: 5400000,
  inventoryHkd: 6100000,
  dsoDays: 52,
  dpoDays: 45,
  inventoryDays: 61,
  grossMarginPercent: 18.5,
  floatingRateDebtHkd: 6500000,
  monthlyDebtServiceHkd: 420000,
  cnySupplierPayablesPercent: 38,
  usdImportCostPercent: 72,
  topCustomerConcentrationPercent: 31,
  workingCapitalGapHkd: 4700000,
  connectedRecords: [
    { id: 'bank-transactions', label: 'Bank transactions', status: 'connected', description: 'HKD and foreign currency bank records' },
    { id: 'invoices', label: 'Invoices', status: 'connected', description: 'Customer billing and sales ledger' },
    { id: 'receivables-aging', label: 'Receivables aging', status: 'connected', description: 'Aging breakdown of customer accounts' },
    { id: 'payables-schedule', label: 'Payables schedule', status: 'connected', description: 'Supplier invoices and schedule' },
    { id: 'debt-schedule', label: 'Debt schedule', status: 'connected', description: 'Floating and fixed corporate loans' },
    { id: 'supplier-contracts', label: 'Supplier contracts', status: 'pending', description: 'Supplier pricing and term sheets' },
  ],
}

export const localServicesLowExposure: CompanyContext = {
  companyName: 'Vanguard Professional Services',
  sector: 'Local Services / Consulting & IT',
  geography: 'HK',
  dataMode: 'connected_workspace',
  revenueTtmHkd: 15000000,
  cashBalanceHkd: 4500000,
  receivablesHkd: 1200000,
  payablesHkd: 400000,
  inventoryHkd: 0,
  dsoDays: 30,
  dpoDays: 30,
  inventoryDays: 0,
  grossMarginPercent: 65.0,
  floatingRateDebtHkd: 500000,
  monthlyDebtServiceHkd: 15000,
  cnySupplierPayablesPercent: 2,
  usdImportCostPercent: 5,
  topCustomerConcentrationPercent: 10,
  workingCapitalGapHkd: 200000,
  connectedRecords: [
    { id: 'bank-transactions', label: 'Bank transactions', status: 'connected', description: 'HKD bank records' },
    { id: 'invoices', label: 'Invoices', status: 'connected', description: 'Client invoices and billings' },
    { id: 'receivables-aging', label: 'Receivables aging', status: 'connected', description: 'Client aging accounts' },
    { id: 'payables-schedule', label: 'Payables schedule', status: 'connected', description: 'Vendor billing schedule' },
    { id: 'debt-schedule', label: 'Debt schedule', status: 'connected', description: 'SME term loan' },
    { id: 'supplier-contracts', label: 'Supplier contracts', status: 'missing', description: 'Procurement contracts' },
  ],
}

export const manufacturingExportPressure: CompanyContext = {
  companyName: 'Apex Precision Manufacturing Ltd.',
  sector: 'Manufacturing / Toys & Hardware Export',
  geography: 'HK / GBA',
  dataMode: 'connected_workspace',
  revenueTtmHkd: 68000000,
  cashBalanceHkd: 1800000,
  receivablesHkd: 18500000,
  payablesHkd: 9200000,
  inventoryHkd: 14000000,
  dsoDays: 78,
  dpoDays: 55,
  inventoryDays: 95,
  grossMarginPercent: 12.0,
  floatingRateDebtHkd: 12000000,
  monthlyDebtServiceHkd: 850000,
  cnySupplierPayablesPercent: 65,
  usdImportCostPercent: 45,
  topCustomerConcentrationPercent: 48,
  workingCapitalGapHkd: 11000000,
  connectedRecords: [
    { id: 'bank-transactions', label: 'Bank transactions', status: 'connected', description: 'Multi-currency corporate accounts' },
    { id: 'invoices', label: 'Invoices', status: 'connected', description: 'Export sales billing data' },
    { id: 'receivables-aging', label: 'Receivables aging', status: 'connected', description: 'Receivables aging breakdown' },
    { id: 'payables-schedule', label: 'Payables schedule', status: 'connected', description: 'Raw material payables schedule' },
    { id: 'debt-schedule', label: 'Debt schedule', status: 'connected', description: 'Receivables financing and credit facilities' },
    { id: 'supplier-contracts', label: 'Supplier contracts', status: 'connected', description: 'GBA components pricing terms' },
  ],
}

export const demoCompanyProfiles = [
  electronicsImportPressure,
  localServicesLowExposure,
  manufacturingExportPressure,
]

export const defaultCompanyProfile = electronicsImportPressure
